#生产环境
spring:
  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: gateway-service
  datasource:
    url: jdbc:mysql://192.168.0.186:3306/springcloud-alibaba-demo?nullCatalogMeansCurrent=true
    hikari:
      username: root
      password: likaladi
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: 192.168.0.186:8848
  #        # 指定namespace（隔离环境:pre,dev等）
  #        namespace: 56116141-d837-4d15-8842-94e153bb6cfb
  #        # 指定集群名称（可以优先地域访问：比如说北京和南京部署了同一集群名称，北京地区的优先访问,如果北京服务宕机，才会访问南京的服务）
  #        cluster-name: BJ
  #        #元数据信息(可以指定多个版本间，同一版本服务访问)
  #        metadata:
  #          instance: c
  #          haha: hehe
  #          version: v1
  rabbitmq:
    host: 192.168.0.186 #连接地址
    port: 5672 #端口号
    username: liwen #账号
    password: likaladi  #密码
    virtual-host: /my_vhost # 虚拟机地址
    ###开启消息确认机制 confirms
    publisher-confirms: true
    publisher-returns: true
