#所有环境公用的配置属性
server:
  port: 8083
spring:
  profiles:
    active: dev


#配置开启sentinel actuator 测试接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always